### PR TITLE
migrated to redmine4 / rails 5.1

### PR DESCRIPTION
**Pull request by bastiedotorg**
compatibility with redmine 4 and rails 5.1

### CODE REVIEW

**Comment by iamacarpet** [comment]
Just tried this on our Redmine 4.0.4 and once installed, the "My Account" page now returns:

"The page you were trying to access doesn't exist or has been removed."

Removing the plugin again fixes the issue.

**Comment by verfriemelt-dot-org** [comment]
i have really no idea how to work with rails / ruby ¯\\\_(ツ)_/¯ but i had some fixes in place before i noticed this pull request and got the plugin working with 4.1-stable! use at your own risk!

https://github.com/verfriemelt-dot-org/redmine_user_specific_theme

**Comment by kporras07** [comment]
I can confirm this PR works. Any chance we get this reviewed/added into main branch?

**Comment by bastiedotorg** [comment]
use this:
https://github.com/t-gergely/redmine_user_specific_theme

works on redmine 5

**Pull request closed without merging**
